FROM fedora:38

RUN dnf -y update
RUN dnf -y group install "Development Tools"
RUN dnf -y install clang autoconf automake libtool git cmake python3 yasm rpmdevtools ninja-build fontconfig-devel qt5-qtbase-devel qt5-qtdeclarative-devel qt5-qtmultimedia-devel qt5-qtsvg-devel zlib-devel
RUN ln -sf /usr/bin/python3 /usr/bin/python

COPY build_docker.sh /
CMD [ "bash", "./build_docker.sh" ]
