# VFX Reference Platform
FROM centos:centos7.9.2009

RUN yum -y update
RUN yum -y install centos-release-scl
RUN yum -y group install "Development Tools"
RUN yum -y install clang git yasm python3 fontconfig-devel zlib-devel autoconf automake xz devtoolset-7 tree curl libICE-devel libSM-devel libX11-devel libXau-devel libXdamage-devel libXext-devel libXfixes-devel libXi-devel libXxf86vm-devel libdrm-devel libxcb-devel mesa-libGL-devel xorg-x11-proto-devel
RUN ln -sf /usr/bin/python3 /usr/bin/python
RUN echo "source scl_source enable devtoolset-7" >> /root/.bashrc

# WIP
# COPY build_vfx.sh /
# CMD [ "bash", "./build_vfx.sh" ]
