FROM rockylinux:9.1

RUN dnf -y install dnf-plugins-core
RUN dnf -y config-manager --enable crb
RUN dnf -y config-manager --enable devel
RUN dnf -y group install "Development Tools"
RUN dnf -y install clang git cmake python3 yasm rpmdevtools ninja-build qt5-devel zlib-devel
RUN ln -sf /usr/bin/python3 /usr/bin/python

COPY build_docker.sh /
CMD [ "bash", "./build_docker.sh" ]
